source 'https://rubygems.org'

gem 'rails', '3.2.11'

group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier',     '1.3.0'
end

group :development, :test do
    gem 'rails-footnotes',  '3.7.9'
    gem 'sqlite3'
end

group :production do
    gem "pg"
end

gem 'paperclip'
gem 'jquery-rails'
gem "bootstrap-sass", ">= 2.3.0.0"
gem "devise", "~> 2.1.2"
gem "quiet_assets", ">= 1.0.1", :group => :development
gem "figaro", ">= 0.5.3", :group => :development
gem "better_errors", ">= 0.6.0", :group => :development
gem "will_paginate", "3.0.4"
gem "binding_of_caller", ">= 0.7.1", :group => :development, :platforms => [:mri_19, :rbx]
gem "thin"